Feature/fixed list pagination
FightPandemics/FightPandemics pull request #1274
Opened 2020-07-26 16:27 UTC by OzkanAbdullahoglu

### What does this pull request aim to achieve? 💯

_Please be concise and link any related issue(s):_

- [ ] I have checked that no one else is working on similar changes.
- [ ] I have read the latest [**README**](https://github.com/FightPandemics/FightPandemics/blob/master/README.md) and understand the development workflow.
- [ ] The name of this branch is: **`feature/<branch_name>`** (need to have cloned the repo not forked).
- [ ] This branch is rebased/merged with the **latest master**.
- [ ] There are no merge conflicts.
- [ ] There are no console warnings and errors.
- [ ] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".

2020-09-09 21:57 UTC, rabbi08 commented
Adding below issue for tracking:
Issue: while loading data for Orgnaisation profile, UI get distorted:

device: iphone 11 pro max
https://share.getcloudapp.com/lluYeAyZ

2020-09-14 16:12 UTC, joshmorel requested changes
Thanks @OzkanAbdullahoglu . 

The loader indicator is working except it still shows up if the filter has no cases:

![image](https://user-images.githubusercontent.com/10546720/93110138-ecf6cc80-f682-11ea-8c4e-533186025135.png)

In such a case we don't want it there - just the message.

Also for profile activity can we also use the loader? It's hard to notice (I need to put devtools network throttling on) - but you see the "No activity" when it is loading (
https://featurefixed-list-pagination.fightpandemics.xyz/organisation/5eff67aa7002103f35cfca9d). Side note: I'm unsure why it's so much faster on activity compared to feed, my guess is - the geo distance sort is skipped).

Otherwise functionality seems good. 

Not sure how much of a deep dive I'll take into the code line-by-line as it's been so dramatically changed for integration with `react-virtualized` library.

2020-09-19 22:01 UTC, OzkanAbdullahoglu commented
@joshmorel @idjevm  Well I tried to cover everything, all edge cases, `emptyFeed()`, `Loader`.  Also, there is a current bug in staging right now.  I added some lines to prevent that one too. 
This is from staging. Current logic loses some of your posts after post deletion and after loading following page. 
![2020-09-20_00-56-24](https://user-images.githubusercontent.com/34690158/93689971-41170c00-fadc-11ea-9414-9a061efdf657.gif)

And yes, Feed.js is a bit slower (in the first mount, on the other hand, scrolling performance is good) cause of filtering. I separated `objectiveURL()` and `filterURL()` from `loadPosts()`, by this way I aimed to not re-run these functions in every re-fetch, just run them when they needed.

2020-09-19 22:29 UTC, OzkanAbdullahoglu commented
React virtualized is a library for rendering large lists more effectively. We use  `WindowScroller` for a full-size scrolling view (like Twitter, Facebook, etc.), `InfiniteLoader`, for fetching when scrolling down, `List` to render elements. 

Examples and docs can be accessed below links.

https://github.com/bvaughn/react-virtualized
https://bvaughn.github.io/react-virtualized/#/components/List

2020-09-21 21:56 UTC, joshmorel approved these changes

2020-09-21 22:03 UTC, joshmorel requested changes

2020-09-21 22:03 UTC, joshmorel commented on client/src/components/Feed/Post.js
>        ) : (
```suggestion
      ) : (
        //Post in feed.
```

I don't think we should remove this comment - it's still helpful.

2020-09-21 22:03 UTC, joshmorel commented on client/src/components/Feed/Post.js
>        ) : (
I will just reset this file to staging & repush

2020-09-21 22:04 UTC, joshmorel approved these changes

2020-09-21 22:56 UTC, OzkanAbdullahoglu commented on client/src/components/Feed/Post.js
>        ) : (
I haven't realised & also do not remember that I removed this comment. anyway, I agree.

2020-09-21 23:01 UTC, idjevm approved these changes
Let's give it a shot! Thanks for all the work on this one @OzkanAbdullahoglu !!!

2020-09-23 11:36 UTC, merged

2020-09-23 16:14 UTC, rabbi08 commented
@idjevm @OzkanAbdullahoglu @joshmorel : Let me know if I should be logging new issue to track below observation:

Tested this PR on mobile and Desktop in STG:
- Desktop version is working fine: 
- Clicking on company profile on mobile, the UI is not distorted as reported above: PASS
- But on the mobile the loading spinner exist along with the message about no post. "Filter" is not working in STG on mobile. : FAIL
Refer below screenshot:
Devices Tested:
- iphone 11 pro max
- Tested on simulator: Samsung Galaxy, iphone XR

Android:
https://share.getcloudapp.com/NQu1LrR6
iOS:
https://share.getcloudapp.com/OAuJ0qxx

2020-09-23 22:10 UTC, OzkanAbdullahoglu commented
Hi @rabbi08 , yes that is my bad, I forgot a simple implementation for mobile. This is an easy fix, I can handle that under a new branch which I will bind to #1545