Error Page created
FightPandemics/FightPandemics pull request #1333
Opened 2020-08-06 19:53 UTC by nadinejuraschek

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix. The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".

closes #1000 

<img width="289" alt="Screen Shot 2020-08-06 at 9 52 14 PM" src="https://user-images.githubusercontent.com/53962732/89576138-25f38400-d82f-11ea-85db-8d3ea5f72882.png">
<img width="1440" alt="Screen Shot 2020-08-06 at 9 51 47 PM" src="https://user-images.githubusercontent.com/53962732/89576143-27bd4780-d82f-11ea-8aa2-857dea3392d1.png">

2020-08-06 20:58 UTC, yu-zhao-xyz approved these changes

2020-08-08 01:07 UTC, idjevm requested changes
Looks good! I would say rename the name of the file though. Maybe as `NotFoundPageError` or `NotFoundPage` or `ErrorPage`. Error is too general.

2020-08-08 15:10 UTC, adisen approved these changes
Apart from what JV said. Looks good.

2020-08-10 21:46 UTC, idjevm approved these changes
Should be good to go! Thanks Nadine!

2020-08-10 21:49 UTC, merged