Added note when no posts are available/highlighted 'Create a Post' button
FightPandemics/FightPandemics pull request #1420
Opened 2020-08-25 05:57 UTC by kterry1

# What does this pull request aim to achieve? 💯
- When no posts are available there is now a note letting the user know there are no posts available and to change the filters or create a post.
- Also, the 'Create a Post' button is highlighted so the user knows where to click when the feed is empty.

Here is a demonstration of it in action: https://share.getcloudapp.com/8LuPp4Q7 

_Please be concise and link any related issue(s):_
Resolves: #1367 

- [X] I have checked that no one else is working on similar changes.
- [X] I have read the latest [**README**](README.md) and understand the development workflow.
- [X] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix. The branch is created in a cloned version of this repo, **not a forked repo**.
- [X] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [X] There are no merge conflicts.
- [X] There are no console warnings and errors.
- [X] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".

2020-08-25 05:59 UTC, kterry1 commented
I tag you both Josue and Josh a lot. Let me know if there is someone else you recommend I tag for review so I'm not bugging you both all the time.

2020-08-25 09:52 UTC, idjevm commented on client/src/pages/Feed.js
> +`
add `;`

2020-08-25 09:55 UTC, idjevm requested changes
Mmmh, I am not sure about this one though, I think we can ask the design team for a design of when there are not posts available... This should be an ok solution meanwhile.

2020-08-25 09:55 UTC, idjevm commented on client/src/pages/Feed.js
> +`
add `;`

2020-08-25 09:55 UTC, idjevm commented on client/src/pages/Feed.js
> +`
add `;`

2020-08-25 09:55 UTC, idjevm commented on client/src/pages/Feed.js
> +
Remove extra line

2020-08-25 09:55 UTC, idjevm commented on client/src/pages/Feed.js
> +
remove extra line

2020-08-25 09:55 UTC, idjevm commented on client/src/pages/Feed.js
> +    };
Check your prettier settings, the formatting seems odd.

2020-08-25 09:55 UTC, idjevm commented on client/src/pages/Feed.js
> +    color: ${theme.colors.orangeRed};
Formatting seems a bit diff here. Perhaps check prettier?

2020-08-25 09:55 UTC, idjevm commented on client/src/pages/Feed.js
> +            {emptyFeed() ? <NoPosts>Sorry, there are currently no relevant posts available. Please try using a different filter search or create a post.</NoPosts>
Please check your prettier settings.

2020-08-25 14:47 UTC, kterry1 commented
Thanks @idjevm. It looks like Prettier wasn't formatting the doc. I made the fix but before I push the new commit up, can we get a design team member to provide another hightlight recommendation? @dhruvdpatel are you able to chime in here since you created #1420.

2020-08-25 16:34 UTC, kterry1 commented
@dhruvdpatel Clarified what he wanted here. I'll make the changes and push it up later today.

2020-08-25 16:58 UTC, kterry1 commented
Here is the new look: https://share.getcloudapp.com/04uqLWvD

I'll push up the code in a bit.

2020-08-25 18:39 UTC, nadinejuraschek approved these changes
lgtm!

2020-08-26 13:14 UTC, idjevm approved these changes
Codewise and logic wise, this makes sense. Could anyone from design check this though? @Yu-Alexa-Zhao , is there a chance your team could take a look at this? We will merge this for now but let's please create a design for this one to make it more nicer looking, etc.

2020-08-26 13:15 UTC, idjevm commented
Will merge this now, any new implementations, please create a new issue, and ask for the design there @dhruvdpatel @tejasm2 @Yu-Alexa-Zhao

2020-08-26 13:15 UTC, merged

2020-08-26 14:18 UTC, Yu-Alexa-Zhao commented
Got it, I will ask the design team to create a better looking no result screen here