#1339 - Password Change Screen
FightPandemics/FightPandemics pull request #1687
Opened 2020-10-21 06:44 UTC by Carrany

### What does this pull request aim to achieve? 💯
Create a Change password screen
_Please be concise and link any related issue(s):_

- [ ] I have checked that no one else is working on similar changes.
- [ ] I have read the latest [**README**](README.md) and understand the development workflow.
- [ ] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [ ] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [ ] There are no merge conflicts.
- [ ] There are no console warnings and errors.
- [ ] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [ ] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

2020-10-21 11:43 UTC, nadinejuraschek submitted a review, later dismissed
I'm not sure what the design looks like for this page, but I am sure the button isn't styled correctly: 
![Screen Shot 2020-10-21 at 1 33 46 PM](https://user-images.githubusercontent.com/53962732/96714242-24ebe080-13a2-11eb-92c3-43ee8410e2cf.png)
It should match the other buttons on our page (purple, no blue border, white text, no box-shadow), could you re-use a button component we already have?

2020-10-22 10:01 UTC, galeza submitted a review, later dismissed
Do we have any design in Figma or Zeplin for this feature?

I think that the design, components are completely different from the style that we have on (for example) Join In screen. Example:
![Screen Shot 2020-10-22 at 11 59 52](https://user-images.githubusercontent.com/21987083/96856582-59bd6d80-145e-11eb-8cde-b194dac9cb28.png)

2020-10-22 20:29 UTC, rabbi08 requested changes
Following issues have been observed while testing:
- The 'New Password' textbox stretch as soon as user start typing.
- The password instructions should not be displayed in single line, as that is the reason it the textbox length vary. the password instruction can be displayed in bulleted list.

![ezgif com-gif-maker (25)](https://user-images.githubusercontent.com/67168400/96926502-a0718e80-1483-11eb-9528-c7caa06c68d7.gif)

- The term 'New Password, confirmation' is not user friendly, it should be 'Confirm Password'

Functional Issue: 
1. After entering all valid values, the password change is unsuccessful. Refer attached screenshot.
2. In the Password change message we have 2 different 'x' close icons which doesn't look appropriate.

![image](https://user-images.githubusercontent.com/67168400/96926155-38bb4380-1483-11eb-9f2f-cfbd2d4decdf.png)

Do we have defined zeplin/figma design to follow.

2020-10-25 15:45 UTC, rabbi08 requested changes
@Carrany 
Is the backend of this features ready to test i.e. Password change functionality is implemented or currently we have to test the UI screen of password change feature. Thanks.

As currently, still after clicking on 'Save Changes' -> The password change is unsuccessful and all the fields are reset. Please see below screenshot,

![image](https://user-images.githubusercontent.com/67168400/97111509-80c1ac80-16b5-11eb-8fa9-18a9fbbd080e.png)

UI Issue:
The 'Edit Profile' option screen, have white screen on the top and all the options are not displayed properly, after scrolling down , there is white space is at the bottom too. Can we adjust all the 3 options of EDIT Profile, without scroll bar by removing the white space?
Please see below GIF.

![ezgif com-gif-maker (27)](https://user-images.githubusercontent.com/67168400/97111603-28d77580-16b6-11eb-9348-84c00c6b2876.gif)

Also, please confirm on the following missing text and link as per the design mentioned in #1339 
- The page should have title as 'Change Your Password'
- Link to 'Forgot Password' should be there on the page.

2020-10-25 15:52 UTC, Carrany commented
@rabbi08 
Backend is ready to test and is working accordingly

2020-10-25 16:34 UTC, rabbi08 commented
@Carrany 
Thanks for confirming. 
I am able to change my password successfully. Please see below GIF.
![ezgif com-gif-maker (28)](https://user-images.githubusercontent.com/67168400/97113063-51636d80-16be-11eb-9dfb-1e29df11342b.gif)

I have following observation, kindly look into these too:
- The 'x' and 'checkbox' sign in the 'Password change successfully/unsuccessfully' should not be there, the message is enough with red cross at the end of the line.
- There are no validation to guide the user if the password change is unsuccessful as if:
  a. if user enter wrong current password, No error message to guide the user.

2020-10-27 13:13 UTC, joshmorel requested changes
We shouldn't commit the `yarn.lock` files. Since we are using `package-lock.json` I think it is best to use npm for installing project dependencies (handled automatically be docker). But in any case, we can add .gitignore for these (I will do). 

**This has been fixed**

2020-10-27 14:07 UTC, joshmorel requested changes
@Carrany as per @rabbi08 question about the wrong existing password. Can we use something similar to Login.js . It is translating the error message from the backend (already translated and it will be the same as with wrong credentials for login).

https://github.com/FightPandemics/FightPandemics/blob/b347a0392498cb682c1de4e1d1110903b0020d62/client/src/pages/Login.js#L267

2020-10-29 19:23 UTC, rabbi08 requested changes, later dismissed
Unable to open EDIT options for individual profile, as after user clicks on Edit icon the screen turn grey on mobile. But the edit icon works fine for org profile. 

Please see below gif
![image](https://user-images.githubusercontent.com/67168400/97622441-abd03700-19fa-11eb-8f27-9f942a39d581.gif)

2020-10-30 13:51 UTC, joshmorel requested changes
Thanks @Carrany . So long as the other issues are confirmed resolved I'm happy with one minor things. Those unused styled components we should remove (I guess you started out using them then switched back to the existing ones used by EditAccount etc?).

Another thing I think we should resolve at a design level. We should have a consistent approach to redirect after editing user/org. In most we are redirecting to profile page but not `edit-organisation-account/` and not here. Actually re-directing back to profile is non-standard UX so it might be better to stay in place BUT we need a better way to navigate on mobile.

2020-10-30 13:51 UTC, joshmorel commented on client/src/components/EditProfile/EditComponents.js
> +export const CustomContainer = styled.div`
I don't see this ones used anywhere.

2020-10-30 17:17 UTC, rabbi08 commented
@Carrany 
- The page title should be 'Change Your Password' not 'Account Information'

Though below scenarios are working fine:
- I am able to change my password- Pass
- wrong current pwd err message is displayed

2020-11-03 13:52 UTC, Carrany commented
@rabbi08 

Account Information is a link to editing account information, not the title of the page. The title of the page is Edit Profile

2020-11-04 06:20 UTC, rabbi08 commented
@Carrany 
On Desktop, the page title is 'Edit Profile' and the TABs have respective names.

But on mobile, every page has its own name: 
- Account Information
- Edit profile 
- "Account Information" for Password change too. Please see below GIF.

![ezgif com-video-to-gif 7](https://user-images.githubusercontent.com/67168400/98076189-ca3f9380-1e3b-11eb-8c7c-0880211c98ea.gif)

2020-11-04 09:12 UTC, Carrany commented
@rabbi08 Please confirm the change from Account Information to Change password on mobile view

2020-11-05 18:40 UTC, rabbi08 approved these changes
Thanks @Carrany 

Verified on mobile and desktop on feature branch as working fine:
- user is able update the pwd successfully
- valid err message is displayed if user enter wrong current pwd

Please see below GIF
![image](https://user-images.githubusercontent.com/67168400/98282553-65378b00-1f6c-11eb-8d2a-456519047b1c.gif)

2020-11-06 14:04 UTC, galeza requested changes
@Carrany 

I have a question about a button: Save Changes. 
On the Join Now screen when passwords don't match we keep button Join Now disabled
with an attribute aria-disabled="true".
![Screen Shot 2020-11-06 at 15 01 02](https://user-images.githubusercontent.com/21987083/98374499-0a239800-2041-11eb-8051-371ee4f8f31c.png)

On the change password edit-security screen Save Changes button looks like enabled - with an attribute aria-disabled="false". 
Maybe it should be : aria-disabled="true" **when passwords don't match**.
![Screen Shot 2020-11-06 at 14 54 08](https://user-images.githubusercontent.com/21987083/98374675-51aa2400-2041-11eb-8447-6d40fcc86b86.png)

2020-11-09 18:13 UTC, rabbi08 commented
@Carrany can we fix this PR and get it merged by today i.e. Monday, Nov 09 EOD, so that we can work on GTM tags for this feature and release to PROD by Tuesday/Wed (Nov 10).

2020-11-12 14:23 UTC, nadinejuraschek approved these changes

2020-11-14 17:19 UTC, rabbi08 commented
Verified the fix on feature branch, the 'Save changes' button remain disable until user enters all the details. 
Thanks

2020-11-14 17:49 UTC, Zaydme approved these changes
LGTM

2020-11-14 19:08 UTC, galeza approved these changes
LGTM

2020-11-17 08:42 UTC, ddveloper commented on backend/lib/endpoints/auth.js
> -      req.log.error(err, "Error logging in");
Will there be other error cases need these 2 lines?

2020-11-17 13:45 UTC, merged