Feature/1930 fixed btn create post org profile
FightPandemics/FightPandemics pull request #1985
Opened 2020-11-30 04:38 UTC by juandelima

### What does this pull request aim to achieve? 💯

_Please be concise and link any related issue(s):_

- [ ] I have checked that no one else is working on similar changes.
- [ ] I have read the latest [**README**](README.md) and understand the development workflow.
- [ ] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [ ] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [ ] There are no merge conflicts.
- [ ] There are no console warnings and errors.
- [ ] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [ ] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

2020-11-30 06:08 UTC, rabbi08 approved these changes
@juandelima 
Verified the fix on feature branch as working fine.
The 'Create post' button is updated for Individual/ Org profile page and help Board page, as shown in below Screenshot. Thanks

![image](https://user-images.githubusercontent.com/67168400/100574486-20bbb880-32a8-11eb-8f9b-f358b618f140.png)

2020-11-30 07:26 UTC, wadehrarshpreet requested changes

2020-11-30 07:26 UTC, wadehrarshpreet commented on client/src/components/Profile/ProfileComponents.js
> +export const btnCreatePostStyle = {
Please use rem instead of px 1 rem = 10px...

2020-11-30 07:26 UTC, wadehrarshpreet commented on client/src/components/Profile/ProfileComponents.js
> +    background-color: #425AF2;
Use reference to royalBlue color from theme

2020-11-30 07:26 UTC, wadehrarshpreet commented on client/src/pages/Feed.js
> +        console.log(page, lastPage, meta.total);
Remove console

2020-11-30 09:55 UTC, ddveloper commented
also please remove the package-lock.json, since there is no new package required

2020-11-30 12:37 UTC, Zaydme requested changes
I wonder what was the reason for modifying the pagination logic?

2020-11-30 12:37 UTC, Zaydme commented on client/src/pages/Profile.js
> +                    onClick={onToggleCreatePostDrawer}
Why do we have the event listener and the GTM id on the parent and the child. It should be only on one element.

2020-11-30 12:37 UTC, Zaydme commented on client/src/pages/OrganisationProfile.js
> +                      onClick={onToggleCreatePostDrawer}
GTM id and the event listener should be only in one element.

2020-11-30 12:37 UTC, Zaydme commented on client/src/pages/Feed.js
> +          );
Don't we need to dispatch the finish loading action here 🤔

2020-11-30 12:37 UTC, Zaydme commented on client/src/pages/Feed.js
> +        } else if (meta.total === limit) {
What was the reason for changing this?

2020-12-08 05:04 UTC, rabbi08 commented
This issue have been fixed in PR #1983.
Hence, closing this issue, feel free to re-open or log new ticket if this issue re-occur. Thanks

2020-12-08 05:04 UTC, closed without merging