test added for GET/api/users
FightPandemics/FightPandemics pull request #2114
Opened 2021-01-02 16:13 UTC by JayashreeSamantasinghar

### What does this pull request aim to achieve? 💯

_Please be concise and link any related issue(s):_

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [x] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

2021-01-04 01:51 UTC, jessica-lau approved these changes, later dismissed
Test passed, LGTM. Please see my suggestion in the code :)

2021-01-04 01:51 UTC, jessica-lau commented on mocha/test/users.test.js
> +const httpStatus = require("http-status");
httpStatus constant isn't being used in the test. I suggest either removing this line or changing line 14 down below from '200' to 'httpStatus.OK'

2021-01-04 16:54 UTC, galeza requested changes
Hi @JayashreeSamantasinghar 
Please, could you rebase or merge staging branch to the feature/api-users. PR #1862 was merged. 
Method `validateStatusCodeResponseBody` was replaced by generic methods:
  ```
  validator.validateResponse(response, {
      statusCode: httpStatus.OK,
    });
    validator.validateResponseBody(response, "firstName", "lastName");
```

2021-01-05 00:46 UTC, jessica-lau approved these changes
@JayashreeSamantasinghar LGTM, retested after you merged staging branch 

![image](https://user-images.githubusercontent.com/56090896/103594002-61b97500-4ec5-11eb-88a0-336d411124be.png)

2021-01-05 17:24 UTC, galeza approved these changes
LGTM

2021-01-05 21:32 UTC, adorapham commented
LGTM. TY 
![image](https://user-images.githubusercontent.com/70918430/103701180-69772900-4f5a-11eb-85c2-ca4f617eb9a8.png)

2021-01-05 21:32 UTC, adorapham commented
LGTM. TY @JayashreeSamantasinghar 
![image](https://user-images.githubusercontent.com/70918430/103701204-76941800-4f5a-11eb-8ffe-65706302613c.png)

2021-01-05 21:33 UTC, adorapham approved these changes

2021-01-06 20:46 UTC, Selbinyyaz approved these changes
Looks great to me. Thank you @JayashreeSamantasinghar 

![Screen Shot 2021-01-06 at 2 43 59 PM](https://user-images.githubusercontent.com/62081140/103818314-e45d4400-502d-11eb-822c-ca9cda584277.png)

2021-01-06 22:26 UTC, JayashreeSamantasinghar commented
Thanks Everyone !! @galeza ,can you please merge this PR if you have access.

2021-01-06 22:36 UTC, merged