Feature/2141 refine result near me
FightPandemics/FightPandemics pull request #2155
Opened 2021-01-16 13:04 UTC by ddveloper

### What does this pull request aim to achieve? 💯
expand searching "NearMe" feature to allow search within range 2k, 5k, 30k, city, state, and country
_Please be concise and link any related issue(s):_
this will fix #2141 

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [x] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

2021-01-17 19:59 UTC, sankethbe commented
@ddveloper Great work! It works very well! By default, It uses location specified in a logged-in user's profile. The same logic based on "Results near me" (using MongoDB geospatial radius queries) can be extended to the location filter too. That way it'll solve all previous issues and work for non logged-in users too.
![image](https://user-images.githubusercontent.com/6366272/104854240-8f71d580-592b-11eb-8b61-4a912d8db1db.png)

2021-01-17 20:07 UTC, ddveloper commented
thanks @sankethbe , I will try combining these location features together, good idea 👍

2021-01-17 22:34 UTC, rabbi08 requested changes
Thanks @ddveloper 
Below are few observations while testing on feature build:
1. For both **Logged-In** and **Non-Logged In** User: The 'Location' filter is not working. It is working in STG. Please below GIF.

![ezgif com-video-to-gif-7](https://user-images.githubusercontent.com/67168400/104857549-4435d380-58e7-11eb-96bd-0eaa8cdf8ba6.gif)

2. When using the "Results near me -> in my country' my recent post/all posts are not displayed. Please below GIF:

![ezgif com-video-to-gif-8](https://user-images.githubusercontent.com/67168400/104857718-5bc18c00-58e8-11eb-9e3f-741acec4ee47.gif)

For 'Results near me'
1. Would like to suggest that as we are implementing sub options, lets display it as dropdown with all the sub options.

2. For adding 'In range of...' sub-options-> can we add both 'km & miles' as distance units because in some countries like US we mention distance in 'miles' so it might not be helpful for US users. 
But I would recommend that lets not display 'In range of' suboptions'
And show "In my city/state/country/worldwide".
 Other reason to recommend this because then this will will match with the 'Post creation -> visibility' criteria too i.e. 'City/State/Country/Worldwide". and 'Worldwide' should be default. 

So, In above case the UI will also display the searched criteria and it will match with the post visibility criteria too. Thanks.
Thoughts?

2021-01-18 00:41 UTC, ddveloper commented
Thanks @rabbi08 , I think `in range of` would still be useful in some cases, while city/state/country are better ones as the primary options

2021-01-18 11:09 UTC, Zaydme reviewed
LGTM!
Great job @ddveloper!
I have left some minor comments

2021-01-18 11:09 UTC, Zaydme commented on backend/lib/endpoints/posts.js
> +
This part might not be very clear and there is probably a better way to do it

2021-01-18 11:09 UTC, Zaydme commented on client/src/pages/Feed.js
> +  }, [searchRange]); // eslint-disable-line react-hooks/exhaustive-deps
This can probably be added to `setQueryFromState`
Not sure if that will cause any problems and the way you did it is good as well.

2021-01-18 19:51 UTC, ddveloper commented
Thanks @Zaydme , I created another PR #2157  (trying to solve current issue without modifying too much), having all these options may be too much for our current data size, will see if that version works or not

2021-02-21 17:59 UTC, ddveloper commented
will be covered by issue #2171 , close this one

2021-02-21 17:59 UTC, closed without merging