Feature/desktop view tabs
FightPandemics/FightPandemics pull request #2223
Opened 2021-02-17 19:53 UTC by clubkemp

First, I know we talked about making the desktop view look like the menu from the help board, but I wanted to get the functionality working and mocked up to the actual designs of Figma before we decided to go that route. I do like this way which matches the Figma designs because it provides consistency for this page across views. Thoughts??

- Adding a utils function to check the window size so that we can change the position of the tabs from top to left
- Using the position property to modify the css of the ProfileTabs styled component so it doesn't break changing to position left/right

Also, I didn't modify the UploadPic component, it's all singe spaces and I can't figure out how to unstag them. I've tried to checkout the specific file from feature/profile-design and staging and I can't get the thing off this PR. Suggestions on how are welcome.
![FightPandemics (1)](https://user-images.githubusercontent.com/5578094/108259908-820c5e80-7116-11eb-9d3b-dc702a1c6dff.gif)

2021-02-17 20:01 UTC, aditilamkhede commented
> First, I know we talked about making the desktop view look like the menu from the help board, but I wanted to get the functionality working and mocked up to the actual designs of Figma before we decided to go that route. I do like this way which matches the Figma designs because it provides consistency for this page across views. Thoughts??
> 
> * Adding a utils function to check the window size so that we can change the position of the tabs from top to left
> * Using the position property to modify the css of the ProfileTabs styled component so it doesn't break changing to position left/right
> 
> Also, I didn't modify the UploadPic component, it's all singe spaces and I can't figure out how to unstag them. I've tried to checkout the specific file from feature/profile-design and staging and I can't get the thing off this PR. Suggestions on how are welcome.
> ![FightPandemics (1)](https://user-images.githubusercontent.com/5578094/108259908-820c5e80-7116-11eb-9d3b-dc702a1c6dff.gif)

Hi @clubkemp yes we should match Figma. Cami confirmed this, it should match figma not Help Board. So great that you followed figma. I will check the PR today and provide my input.

2021-02-17 23:02 UTC, aditilamkhede requested changes
@clubkemp  Also in profile.js, line 352 or similar where you have defined const tabViews = {
in tabs property, tabs should be able to adjust based on conditional statement. For example, for own view we will see requests and posts menu but for others view we should see only Posts tab. When I tried it it shows a clear gap i.e. if menu is hidden there is a big gap between 2 menu tabs.
This is showing all tabs
<img width="838" alt="Screen Shot 2021-02-17 at 2 59 43 PM" src="https://user-images.githubusercontent.com/22331887/108279146-fa801900-7130-11eb-9ee5-71e27559bd04.png">
Hiding tab
<img width="827" alt="Screen Shot 2021-02-17 at 2 59 22 PM" src="https://user-images.githubusercontent.com/22331887/108279148-fb18af80-7130-11eb-8f5a-5ad3ee5782c4.png">

2021-02-17 23:02 UTC, aditilamkhede commented on client/src/pages/Profile.js
> +    position: window.width < 800 ? "top" : "left",
@clubkemp instead of hardcoding the values here and creating a utility function. use this 
  window.screen.width <= parseInt(mq.phone.wide.maxWidth);
 first thing is no hardcoding, second for all types of screens theres is screen size defined in themes.js, that way if changes are required it will be at just one place.
Also, to note that, any screensize 767 or less is mobile screen, 800 might fail some scenarios.

2021-02-18 01:12 UTC, clubkemp commented on client/src/pages/Profile.js
> +    position: window.width < 800 ? "top" : "left",
Makes sense. So where does mq come from? Is there already a dev dependency that we can pull that from or are you suggesting we npm install something like react-responsive?

2021-02-18 07:16 UTC, aditilamkhede commented on client/src/pages/Profile.js
> +    position: window.width < 800 ? "top" : "left",
It's in theme.js --> import { theme, mq } from "constants/theme";

2021-02-18 07:17 UTC, aditilamkhede commented
> @clubkemp Also in profile.js, line 352 or similar where you have defined const tabViews = {
> in tabs property, tabs should be able to adjust based on conditional statement. For example, for own view we will see requests and posts menu but for others view we should see only Posts tab. When I tried it it shows a clear gap i.e. if menu is hidden there is a big gap between 2 menu tabs.
> This is showing all tabs
> <img alt="Screen Shot 2021-02-17 at 2 59 43 PM" width="838" src="https://user-images.githubusercontent.com/22331887/108279146-fa801900-7130-11eb-9ee5-71e27559bd04.png">
> Hiding tab
> <img alt="Screen Shot 2021-02-17 at 2 59 22 PM" width="827" src="https://user-images.githubusercontent.com/22331887/108279148-fb18af80-7130-11eb-8f5a-5ad3ee5782c4.png">

@clubkemp I hope you also noticed this as well.

2021-02-18 20:37 UTC, aditilamkhede commented on client/src/pages/Profile.js
> +    position: window.width < 800 ? "top" : "left",
@clubkemp also try to use rem wherever possible instead of px.

2021-02-19 23:37 UTC, aditilamkhede approved these changes

2021-02-21 23:23 UTC, merged