Feature/2171 sort options dropdown
FightPandemics/FightPandemics pull request #2229
Opened 2021-02-22 03:07 UTC by clubkemp

Creating a dropdown for the sort feature for once we have our backend sorted out. The dropdown takes in a callback handleSortDropdown which we can use to fire whatever sorting features we come up with

I had to slightly modify the BaseSelector component to no longer have a parent container function in there. I backtracked it to the only other dropdown I could find and made sure it was still working. Posted about it in the general engineering channel but didn't hear anything

![FightPandemics (2)](https://user-images.githubusercontent.com/5578094/108651951-ba45d100-7477-11eb-9e56-912dbd82a971.gif)

2021-02-24 06:46 UTC, ddveloper commented
Thanks @clubkemp , is there a mobile view dropdown for the same component? I don't see that in the mobile view

2021-02-25 20:22 UTC, clubkemp reviewed
@ddveloper, the notion board didn't really include mobile view information so I just left it out, but you are right, should just be included.
 
https://www.notion.so/fightpandemics/Filters-Sort-By-Feed-e14712b0687749628c09947363e74e88

I went ahead and am using some ternary logic to display the dropdown component in two different places based on mobile view or not
![FightPandemics (5)](https://user-images.githubusercontent.com/5578094/109212033-e5743d00-7763-11eb-85db-e0edae2c5659.gif)

2021-02-26 04:17 UTC, linadinh2602 commented on client/src/components/Selector/Selector.js
> +  // const checkPopUp = () =>{
is this comment out?

2021-02-26 04:23 UTC, linadinh2602 requested changes
There is a comment out I think you forgot to delete. Feel free to merge after that

2021-02-26 23:48 UTC, merged